### ISSUE TITLE
vytvorit skorovaci system

### ISSUE THREAD

**Issue by holkovic** [JozefCulen/123-zombie#20]
Pri sputeni hry sa zacne s nejakym mnozstvem penez (zatal bych ulozene hry neriesil). Po skonceni kazdej mapy by sa mal zvysit pocet penazi. Toto mnozstvo by sa malo uchovavat v nejakej premennej aby sa to furt neresetovalo. Tato premenna by zaroven mala byt zobrazena nekde v menu (asi pri vybere auta/mapy).

**Comment by marhoSVK** [comment]
Vytvorený nový script GameControl.cs, ktorý sa stará o prácu so sejvami. Pri načítaní každej scény sa musí spustiť metoda "GameControl.Load ();" a pri ukončení scény (tesne pred presmerovaním) metoda "GameControl.Save ();" . Dáta budú ukladané v GameControl.save avšak je nutné najprv poriešiť ako štruktúru sejvov bude mať podobu.
